---
title: "SAM simétrico y asimétrico"
author: "Elio Campitelli"
output: 
   # pdf_document:
   #    latex_engine: xelatex
   powerpoint_presentation:
    # ioslides_presentation:
        fig_height: 7.6
        fig_width: 12.8
        reference_doc: "../templates/template.pptx" 
        slide_level: 2
urlcolor: blue
header_includes:
   - \usepackage[utf8]{inputenc}
---

<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

<!-- With the following code you can access and display values from the yml header above. -->
<!-- 
Keywords: `r rmarkdown::metadata$keywords`

Highlights: `r rmarkdown::metadata$highlights`
-->

<!-- The following code chunk defines some general settings how code chunks should behave. -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 300
)

library(metR)
library(data.table)
library(ggplot2)
library(magrittr)
library(ggperiodic)
library(asymsam)

theme_set(theme_asymsam())
ZeroBreaks <- AnchorBreaks(0, NULL, 0)

lev.lab <- AddSuffix(" hPa")

guide_colorstrip_bottom <- function(width = 25, height = 0.5, ...) {
  guide_colorstrip(title.position = "top", title.hjust = 0.5,
                   barheight = height,
                   barwidth = width, ...)
}

main_levs <- c(700, 300, 30)
```


```{r read-hgt}
hgt <- ReadNetCDF(ERA5(), 
                  subset = list(time = c("1979-01-01", "2018-12-31"),
                                latitude = c(-90, 10),
                                level = as.list(main_levs)),
                  vars = c(hgt = "z")) %>% 
  normalise_coords() %>% 
  .[, hgt := hgt/9.8] %>% 
  .[, hgt_a := hgt - mean(hgt), by = .(lon, lat, lev, month(time))]
```

```{r compute-SAM}
SAM <- hgt[lat <= -20] %>% 
  .[, hgt := hgt_a*sqrt(cos(lat*pi/180))] %>% 
  .[, .(eof = list(eof_flip(EOF(hgt ~ time | lon + lat, n = 1, data = .SD)))), 
    by = .(lev)]
```


<!-- The actual document text starts here: -->

# Introduction


# Methods


```{r method, fig.cap = "Spatial patterns of the first EOF of 700 hPa geopotential height. Full field (left), zonally asymmetric component (middle) and zonally symmetric component (right). Arbitrary units."}
sam_sep <- SAM[, eof[[1]]$right, by = .(lev)] %>% 
  setnames("hgt", "full") %>% 
  .[, c("sym", "asym") := list(mean(full), Anomaly(full)), by = .(lat, lev)]


lab_sam <-  c(full = "Full", 
              asym = "Asymmetric",
              sym  = "Symmetric")

sam_sep %>% 
  .[lev == 700] %>%
  rm_singleton() %>% 
  melt(id.vars = c("lon", "lat")) %>% 
  
  # .[variable == "asym", value := value + rnorm(.N, 0, sd = 1e-6)] %>%
  .[, variable := factor(variable, levels = names(lab_sam), ordered = TRUE)] %>% 
  periodic(lon = c(0, 360)) %>% 
  ggplot(aes(lon, lat)) +
  # geom_contour2(aes(z = value, linetype = factor(-sign(..level..))), global.breaks = FALSE) +
  geom_contour_fill(aes(z = value), global.breaks = FALSE) +
  geom_contour_tanaka(aes(z = value), global.breaks = FALSE) +
  geom_qmap() +
  scale_x_longitude() +
  scale_y_latitude(limits = c(NA, -20)) +
  scale_fill_divergent(guide = "none") +
  coord_polar() +
  facet_grid(~variable, labeller = labeller(variable = lab_sam, lev = lev.lab)) 
```


# Results


```{r compute-asymsam}
indexes_file <- data_path("derived", "indexes.Rds")
if (file.exists(indexes_file)) {
  indexes <- readRDS(indexes_file)
} else {
  stop("Run 02-compute-eofs.R")
}


indexes_wide <- dcast(indexes, + lev + time ~ term, value.var = "estimate_norm")
```

```{r asymsam-timeseries, fig.cap = "Time series for the asymmetric SAM and symmetric SAM."}
indexes %>% 
  .[lev %in% c(30, 700) & term != "full"] %>% 
  ggplot(aes(time, estimate_norm)) +
  geom_line(aes(color = term)) +
  # geom_smooth(method = "lm", aes(color = term)) +
  scale_color_brewer(NULL, palette = "Set1", labels = lab_sam) +
  scale_y_continuous(NULL) +
  scale_x_datetime(NULL) +
  facet_grid(lev~., labeller = labeller(lev = lev.lab))
```

```{r asymsam-timeseries-seasonally, fig.cap = "Seasonal time series for the asymmetric SAM and symmetric SAM."}
indexes %>% 
  .[lev %in% c(30, 700) & term != "full"] %>% 
  .[, .(estimate_norm = mean(estimate_norm)), by = .(term, lev, time = seasonally(time))] %>% 
  .[, season := season(time)] %>% 
  ggplot(aes(time, estimate_norm)) +
  geom_line(aes(color = term)) +
  # geom_smooth(method = "lm", aes(color = term)) +
  scale_color_brewer(NULL, palette = "Set1", labels = lab_sam) +
  scale_y_continuous(NULL) +
  scale_x_datetime(NULL) +
  facet_grid(season~lev, labeller = labeller(lev = lev.lab))
```


```{r cor-lev, fig.cap = "Correlation between the Symmetric and Asymmetric SAM at each level."}
indexes_wide[, cor(asym, sym), by = lev] %>% 
  ggplot(aes(lev, V1)) +
  geom_line() +
  scale_x_level() + 
  scale_y_continuous("Correlation", limits = c(0, 1)) + 
  coord_flip()
```

```{r cross-correlation, fig.cap = "Cross correlation between levels of the Full, Asymmetric and Symmetric SAM."}
indexes %>% 
  copy() %>% 
  .[, widyr::pairwise_cor(.SD, lev, time, estimate), by = .(term)] %>% 
  ggplot(aes(item1, item2)) +
  geom_contour_fill(aes(z = correlation), na.fill = 1) +
  scale_fill_divergent("Cross-correlation") +
  scale_x_level() +
  scale_y_level() +
  coord_equal() +
  facet_grid(. ~ term, labeller = labeller(term = lab_sam))
```

```{r compute-regr-pattern}
indexes_2d <- hgt[lev %in% main_levs] %>% 
  indexes_wide[., on = .NATURAL, allow.cartesian = TRUE] %>% 
  .[, rbind(as.data.table(FitLm(hgt_a, sym, asym)),
            as.data.table(FitLm(hgt_a, full))),
    by = .(lon, lat, lev)] %>% 
  rm_intercept() %>% 
  periodic(lon = c(0, 360)) %>% 
  .[, term := factor(term, levels = names(lab_sam), ordered = TRUE)] 
```


```{r 2d-regr, fig.cap = "Regression patterns of geopotential height at 30, 300 and 700 hPa with the Full, Asymmetric and Symmetric SAM. The regression patterns for Asymmetric and Symmetric SAM are the result of one multiple regression using both indices, not of two simple regressions involving each index by itsef."}
indexes_2d %>% 
  .[lat <= -20] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), breaks = ZeroBreaks, global.breaks = FALSE) +
  # geom_contour2(aes(z = estimate, linetype = factor(-sign(..level..))), 
  # size = 0.3,
  # global.breaks = FALSE) +
  geom_contour_tanaka(aes(z = estimate),
                      breaks = ZeroBreaks,
                      size = 0.3,
                      global.breaks = FALSE) +
  geom_qmap(~.x[lat <= -20]) +
  # geom_contour2(data = ~.x[dataset == "NCEP"], aes(z = V1)) +
  scale_x_longitude() +
  scale_y_latitude(limits = c(NA, -20)) +
  scale_fill_divergent(NULL, guide = guide_colorstrip_bottom(), 
                       limits = c(-80, 80),
                       oob = scales::squish,
                       breaks = MakeBreaks(binwidth = 20, exclude = 0)) +
  scale_linetype(guide = "none") +
  coord_polar() +
  facet_grid(term ~ lev, labeller = labeller(term = lab_sam, lev = lev.lab))
```


```{r compute-regr-pattern-season}
indexes_2d <- hgt[lev %in% main_levs] %>% 
  indexes_wide[., on = .NATURAL, allow.cartesian = TRUE] %>% 
  .[, rbind(as.data.table(FitLm(hgt_a, sym, asym)),
            as.data.table(FitLm(hgt_a, full))),
    by = .(lon, lat, lev, season(time))] %>% 
  rm_intercept() %>% 
  periodic(lon = c(0, 360)) %>% 
  .[, term := factor(term, levels = names(lab_sam), ordered = TRUE)] 

```

```{r 2d-regr-700, fig.cap = "Seasonal regression patterns of geopotential height at 700 hPa with the Full, Asymmetric and Symmetric SAM. The regression patterns for Asymmetric and Symmetric SAM are the result of one multiple regression using both indices, not of two simple regressions involving each index by itsef."}
indexes_2d %>% 
  .[lat <= -20] %>% 
  .[lev == 700] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), breaks = ZeroBreaks, global.breaks = FALSE) +
  # geom_contour2(aes(z = estimate, linetype = factor(-sign(..level..))), 
  # size = 0.3,
  # global.breaks = FALSE) +
  geom_contour_tanaka(aes(z = estimate),
                      breaks = ZeroBreaks,
                      size = 0.3,
                      global.breaks = FALSE) +
  geom_qmap(~.x[lat <= -20]) +
  # geom_contour2(data = ~.x[dataset == "NCEP"], aes(z = V1)) +
  scale_x_longitude() +
  scale_y_latitude(limits = c(NA, -20)) +
  scale_fill_divergent(NULL, guide = guide_colorstrip_bottom(), 
                       limits = c(-80, 80),
                       oob = scales::squish,
                       breaks = MakeBreaks(binwidth = 20, exclude = 0)) +
  scale_linetype(guide = "none") +
  coord_polar() +
  facet_grid(term ~ season, labeller = labeller(term = lab_sam, lev = lev.lab))
```

```{r 2d-regr-30, fig.cap = "Seasonal regression patterns of geopotential height at 30 hPa with the Full, Asymmetric and Symmetric SAM. The regression patterns for Asymmetric and Symmetric SAM are the result of one multiple regression using both indices, not of two simple regressions involving each index by itsef."}
indexes_2d %>% 
  .[lat <= -20] %>% 
  .[lev == 30] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), breaks = ZeroBreaks, global.breaks = FALSE) +
  # geom_contour2(aes(z = estimate, linetype = factor(-sign(..level..))), 
  # size = 0.3,
  # global.breaks = FALSE) +
  geom_contour_tanaka(aes(z = estimate),
                      breaks = ZeroBreaks,
                      size = 0.3,
                      global.breaks = FALSE) +
  geom_qmap(~.x[lat <= -20]) +
  # geom_contour2(data = ~.x[dataset == "NCEP"], aes(z = V1)) +
  scale_x_longitude() +
  scale_y_latitude(limits = c(NA, -20)) +
  scale_fill_divergent(NULL, guide = guide_colorstrip_bottom(), 
                       limits = c(-80, 80),
                       oob = scales::squish,
                       breaks = MakeBreaks(binwidth = 20, exclude = 0)) +
  scale_linetype(guide = "none") +
  coord_polar() +
  facet_grid(term ~ season, labeller = labeller(term = lab_sam, lev = lev.lab))
```


```{r wave-amplitude-700, fig.cap = "Planteray wave squared amplitudes for the regression patterns at 700 hPa."}
indexes_2d %>% 
  .[ lev == 700 & lat < -20] %>%
  .[, FitWave(estimate, 1:3), by = .(lat, lev, season, term)] %>% 
  ggplot(aes(lat, amplitude^2)) +
  geom_line(aes(color = factor(k))) +
  scale_color_brewer("Wave-number", palette = "Set1") +
  scale_y_continuous("Squared amplitude") +
  scale_x_latitude(ticks = 15) +
  coord_flip() +
  facet_grid(term~season, labeller = labeller(term = lab_sam)) 
```

```{r wave-amplitude-30, fig.cap = "Planteray wave squared amplitudes for the regression patterns at 30 hPa."}
indexes_2d %>% 
  .[ lev == 30 & lat < -20] %>%
  .[, FitWave(estimate, 1:3), by = .(lat, lev, season, term)] %>% 
  ggplot(aes(lat, amplitude^2)) +
  geom_line(aes(color = factor(k))) +
  scale_color_brewer("Wave-number", palette = "Set1") +
  scale_y_continuous("Squared amplitude") +
  scale_x_latitude(ticks = 15) +
  coord_flip() +
  facet_grid(term~season, labeller = labeller(term = lab_sam)) 
```

```{r compute-pp-regr} 
pp <- CMAP() %>% 
  ReadNetCDF() %>% 
  normalise_coords() %>% 
  .[, precip := Anomaly(precip), by = .(lon, lat)]

pp_regr <- pp %>% 
  .[indexes_wide[lev == 700], on = .NATURAL] %>% 
  .[, FitLm(precip, asym, sym, se = TRUE, r2 = TRUE), by = .(lon, lat)] %>% 
  rm_intercept() %>% 
  .[, p.value := Pvaluate(estimate, std.error, df, "fdr"), by = .(term)]
```


```{r regr-pp, fig.cap = "Regression pattern of precipiation with Asymmetric and Symmetric SAM. P-values smaller than 0.05 (controlling for Flase Detection Rate) as hatched areas."}
pp_regr %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), na.fill = TRUE, breaks = AnchorBreaks(0, 0.1, 0)) +
  geom_contour2(aes(z = p.value), breaks = 0.01) +
  geom_contour_fill(aes(z = as.numeric(is.na(estimate))), breaks = 1) +
  stat_subset(aes(subset = p.value <= 0.01 & is.cross(lon, lat)), size = 0.4, alpha = 0.3) +
  geom_qmap() +
  scale_x_longitude() +
  scale_y_latitude() +
  scale_fill_divergent("Precipitation", guide = guide_colorstrip_bottom(), 
                       breaks = AnchorBreaks(0, 0.1, 0)) +
  coord_quickmap() +
  facet_wrap(~term, labeller = labeller(term = lab_sam))
```

```{r regr-pp-season, fig.cap = "Regression pattern of precipiation with Asymmetric and Symmetric SAM. P-values smaller than 0.05 (controlling for Flase Detection Rate) as hatched areas."}
pp_regr_season <- pp %>% 
  # .[, air := Anomaly(air), by = .(lon, lat)] %>%
  .[indexes_wide[lev == 700], on = .NATURAL] %>% 
  rm_singleton() %>% 
  .[, lapply(.SD, mean, na.rm = TRUE), by = .(lon, lat, time = seasonally(time))] %>%
  .[, nas := mean(is.na(precip)), by = .(lon, lat, season(time))] %>% 
  .[nas >= 0.15, precip := NA] %>% 
  .[, rbind(as.data.table(FitLm(precip, asym, sym, se = TRUE)),
            as.data.table(FitLm(precip, full, se = TRUE))),
    by = .(lon, lat, season(time))] %>% 
  rm_intercept() %>% 
  .[, p.value := Pvaluate(estimate, std.error, df, "fdr"), by = .(season, term)]

pp_regr_season %>% 
  ggplot(aes(lon, lat)) +
  # geom_raster(aes(fill = estimate)) +
  geom_contour_fill(aes(z = estimate), na.fill = 0, breaks = AnchorBreaks(0, 0.5, 0)) +
  geom_contour2(aes(z = p.value), breaks = 0.01) +
  geom_contour_fill(aes(z = as.numeric(is.na(estimate))), breaks = 1) +
  stat_subset(aes(subset = p.value <= 0.01 & is.cross(lon, lat)), size = 0.4, alpha = 0.3) +
  geom_qmap() +
  scale_x_longitude() +
  scale_y_latitude() +
  scale_fill_divergent("Precipitation", guide = guide_colorstrip_bottom(), 
                       breaks = AnchorBreaks(0, 0.5, 0)) +
  coord_quickmap() +
  facet_grid(season~term, labeller = labeller(term = lab_sam))
```


```{r compute-air-regr}
time_subset <- list(time = range(indexes$time))
air <- NOAATemp() %>% 
  ReadNetCDF(vars = "air", subset = time_subset) %>% 
  normalise_coords() 

air_regr <- air %>%
  copy() %>% 
  .[, nas := mean(is.na(air)), by = .(lon, lat)] %>% 
  .[nas >= 0.15, air := NA] %>% 
  # .[, air := Anomaly(air), by = .(lon, lat)] %>%
  .[indexes_wide[lev == 700], on = .NATURAL] %>% 
  .[, rbind(as.data.table(FitLm(air, asym, sym, se = TRUE)),
            as.data.table(FitLm(air, full, se = TRUE))),
    by = .(lon, lat)] %>% 
  rm_intercept()
```

```{r regr-air, fig.cap = "Regression pattern of surface temperature with Asymmetric and Symmetric SAM. P-values smaller than 0.05 (controlling for Flase Detection Rate) as hatched areas."}
air_regr %>%
  copy() %>% 
  .[lat <= -60, estimate := NA] %>%
  .[, p.value := Pvaluate(estimate, std.error, df, "fdr"), by = .(term)] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), na.fill = 0,
                    breaks = AnchorBreaks(0, 0.05, 0)) +
  geom_contour2(aes(z = p.value), breaks = 0.05) +
  stat_subset(aes(subset = p.value <= 0.05 & is.cross(lon, lat)), size = 0.4, alpha = 0.8) +
  stat_subset(aes(subset = is.na(estimate)), geom = "raster", fill = "gray50") +
  geom_qmap() +
  scale_x_longitude() +
  scale_y_latitude() +
  scale_fill_divergent("Surface temperature", 
                       guide = guide_colorstrip_bottom(), breaks = AnchorBreaks(0, 0.05, 0)) +
  coord_quickmap() +
  facet_grid(.~term, labeller = labeller(term = lab_sam))
```

```{r regr-air-season, fig.cap = "Regression pattern of surface temperature with Asymmetric and Symmetric SAM. P-values smaller than 0.05 (controlling for Flase Detection Rate) as hatched areas."}
air_regr_season <- air %>% 
  # .[, air := Anomaly(air), by = .(lon, lat)] %>%
  .[indexes_wide[lev == 700], on = .NATURAL] %>% 
  rm_singleton() %>% 
  .[, lapply(.SD, mean, na.rm = TRUE), by = .(lon, lat, time = seasonally(time))] %>%
  .[, nas := mean(is.na(air)), by = .(lon, lat, season(time))] %>% 
  .[nas >= 0.15, air := NA] %>% 
  .[, rbind(as.data.table(FitLm(air, asym, sym, se = TRUE)),
            as.data.table(FitLm(air, full, se = TRUE))),
    by = .(lon, lat, season(time))] %>% 
  rm_intercept() 

air_regr_season %>% 
  copy() %>% 
  .[lat <= -61, estimate := NA] %>%
  .[lat >= 65, estimate := NA] %>%
  .[, p.value := Pvaluate(estimate, std.error, df, "fdr"), by = .(term, season)] %>% 
  ggplot(aes(lon, lat)) +
  geom_contour_fill(aes(z = estimate), na.fill = 0,
                    breaks = AnchorBreaks(0, 0.15, 0)) +
  # geom_raster(aes(fill = estimate)) +
  geom_contour2(aes(z = p.value), breaks = 0.05) +
  stat_subset(aes(subset = p.value <= 0.05 & is.cross(lon, lat)), size = 0.4, alpha = 0.8) +
  stat_subset(aes(subset = is.na(estimate)), geom = "raster", fill = "gray50") +
  geom_qmap() +
  scale_x_longitude() +
  scale_y_latitude() +
  scale_fill_divergent("Surface temperature",  limits = c(-0.8, .8), oob = scales::squish,
                       guide = guide_colorstrip_bottom(), breaks = AnchorBreaks(0, 0.15, 0)) +
  coord_quickmap() +
  facet_grid(season~term, labeller = labeller(term = lab_sam))
```


# Discussion

# Conclusion

# Acknowledgements

<!-- The following line inserts a page break  -->

\newpage

# References 

<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->

<div id="refs"></div>

\newpage

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
if ("devtools" %in% installed.packages()) devtools::session_info()
```

The current Git commit details are:

```{r git-info, cache = FALSE}
# what commit is this file at? 
if ("git2r" %in% installed.packages() & git2r::in_repository(path = ".")) git2r::repository(here::here())  
```
