---
title: "Teasing out the asymmetric component of the Southern Annular Mode"
output: pdf_document
---

The conception of the Southern Annular Mode as a mostly zonally symmetric pattern is reflected not only in its name, but also on the various methods used to characterise it. Gong and Wang (1999) and many others define the SAM index based on zonal mean pressure anomalies. Baldwind & Thompson also put forward an index based on performin EOF on zonal mean geopotential height. However, composites and regression patterns based on these indices consistently result in zonally assymetric patterns partially embebed in the zonally symmetric structure. Citar a @fogt2012 de alguna manera? Here, we propose a straightforward method of creating two sister indices of Symemtric and Asymmetric SAM and show that they can be used to separate between the zonally symmetric and asymmetric structure. We show that the observed trends towards more positive SAM [@folgt2020] is completely explained by the Symmetric component, but that the relationship between SAM and surface variables such as temperature and precipitation is associated more strongly with the Asymmetric component, particularly over the Southern continents. 


```{r eval=FALSE, include=FALSE}
nchar(gsub(" ", "", "The conception of the Southern Annular Mode as a mostly zonally symmetric pattern is reflected not only in its name, but also on the various methods used to characterise it. Gong and Wang (1999) and many others define the SAM index based on zonal mean pressure anomalies. Baldwind & Thompson also put forward an index based on performin EOF on zonal mean geopotential height. However, composites and regression patterns based on these indices consistently result in zonally assymetric patterns partially embebed in the zonally symmetric structure. Citar a @fogt2012 de alguna manera? Here, we propose a straightforward method of creating two sister indices of Symemtric and Asymmetric SAM and show that they can be used to separate between the zonally symmetric and asymmetric structure. We show that the observed trends towards more positive SAM [@folgt2020] is completely explained by the Symmetric component, but that the relationship between SAM and surface variables such as temperature and precipitation is associated more strongly with the Asymmetric component, particularly over the Southern continents."))
```

